-- CONSULTAR OS DADOS

SELECT * FROM USUARIO WHERE ACESSO='user'
SELECT * FROM USUARIO WHERE ACESSO='admin'

SELECT * FROM USUARIO 
WHERE EMAIL='doug@gmail.com'
AND SENHA='dudu123'


SELECT * FROM USUARIO
WHERE EMAIL LIKE '%@gmail%'
