CREATE DATABASE LOJINHA; 
USE LOJINHA
CREATE TABLE USUARIOS (
	ID INT PRIMARY KEY IDENTITY,
	NOME VARCHAR (50) NOT NULL,
	EMAIL VARCHAR (319) NOT NULL UNIQUE,
	DT_NASC DATE NOT NULL,
	SENHA CHAR(32) NOT NULL
);