-- CONSULTAS COMPLEXAS

-- 1) LISTAR OS NOMES E O EMAIL DOS CLIENTES 
SELECT NOME, EMAIL FROM CLIENTE 


-- 2)LISTAR EMAIL E SENHA DOS CLIENTES 
SELECT EMAIL, SENHA FROM CLIENTE

-- 3) PEGAR OS DADOS DESTE USUARIO DE EMAIL maria.oliveira@example.com E SENHA senha123
SELECT * FROM CLIENTE
WHERE EMAIL='maria.oliveira@example.com' AND SENHA='senha123'

-- 4) O TITULO E O PRECO DOS PROODUTOS 
SELECT ID, titulo, preco FROM produto

-- 5) DADOS DOS PODUTOS COM SUAS IMAGENS
SELECT * FROM PRODUTO P, IMAGEM I
WHERE P.ID = I.id_produto
-- USANDO O JOIN
SELECT * FROM PRODUTO P JOIN IMAGEM I
ON P.ID = I.id_produto

-- 6) BUSCAR NOME DO CLIENTE E TOTAL GASTO (AGRUPAMENTO)
SELECT C.ID, NOME,SUM(TOTAL) TOTAL FROM CLIENTE C,PEDIDO P
WHERE C.ID = id_cliente
GROUP BY C.ID, NOME

-- 7) BUSCAR OS DADOS DO PEDIDO, INCLUINDO OS DADOS DOS PRODUTOS
SELECT * FROM PEDIDO PD, ITEM_PEDIDO IT, PRODUTO PR, PRODUTO P, IMAGEM I
WHERE PD.ID = ID_PEDIDO AND PR.ID = IT.ID_PRODUTO AND P.ID = I.id_produto
-- USANDO JOIN
SELECT PD.ID,DATA_PEDIDO, IT.QUANTIDADE, PR.TITULO 
FROM PEDIDO PD 
JOIN ITEM_PEDIDO IT
ON PD.ID = ID_PEDIDO
JOIN PRODUTO PR
ON PR.ID = IT.ID_PRODUTO


-- 8) AS INFORMAÇÕES DO SELECT ANTERIOR COM AS IMAGENS DOS PRODUTOS
SELECT C.NOME, PD.ID,DATA_PEDIDO, IT.QUANTIDADE, PR.TITULO ,I.LINK
FROM CLIENTE C 
JOIN PEDIDO PD ON C.ID = PD.ID_CLIENTE
JOIN ITEM_PEDIDO IT ON PD.ID = ID_PEDIDO
JOIN PRODUTO PR ON PR.ID = IT.ID_PRODUTO
JOIN IMAGEM I ON PD.ID = I.id_produto
WHERE NOME = 'MARIA'

-- 9)TODOS OS PEDIDOS DA MARIA COM SEUS PRODUTOS

SELECT * FROM CLIENTE C 
JOIN  PEDIDO PD ON C.ID_CLIENTE 