CREATE DATABASE BDCOMPRAS 
USE BDCOMPRAS

CREATE TABLE CLIENTES  
(CODCLI INT NOT NULL PRIMARY KEY, 
NOMECLI VARCHAR(30), 
ENDERECO VARCHAR(50)) 

sp_help Clientes 

CREATE TABLE FORNECEDORES 
(CODFORN INT NOT NULL PRIMARY KEY, 
NOMEFORN VARCHAR(50), 
ENDERECO VARCHAR(100)) 

sp_help Fornecedores 

CREATE TABLE PRODUTOS 
(CODPROD INT NOT NULL PRIMARY KEY, 
NOMEPROD VARCHAR(50), 
VALOR MONEY, 
CODFORN INT NOT NULL, 
FOREIGN KEY (CODFORN) REFERENCES FORNECEDORES) 

sp_help Produtos 

CREATE TABLE COMPRAS 
(CODCLI INT NOT NULL, 
CODPROD INT NOT NULL, 
QTDE INT, 
FORMAPAGTO VARCHAR(30), 
DATACOMPRA SMALLDATETIME, 
PRIMARY KEY(CODCLI,CODPROD), 
FOREIGN KEY (CODPROD) REFERENCES PRODUTOS, 
FOREIGN KEY (CODCLI) REFERENCES CLIENTES) 

sp_help Compras 