CREATE DATABASE BDESCOLA
USE BDESCOLA

CREATE TABLE LIVROS
(
ISBN INT NOT NULL PRIMARY KEY,
TITULO VARCHAR(100) NOT NULL
);

CREATE TABLE ALUNOS 
(
MATRICULA_ALUNO INT NOT NULL PRIMARY KEY,
NOME_ALUNO VARCHAR(2500) NOT NULL 
);

CREATE TABLE CURSOS
(
CODIGO_CURSO INT NOT NULL PRIMARY KEY,
DESCRICAO_CURSO TEXT NOT NULL 
);

CREATE TABLE DISCIPLINAS
(
CODIGO_DISCIPLINA INT NOT NULL PRIMARY KEY,
DESCRICAO_DISCIPLINA TEXT NOT NULL 
);

CREATE TABLE PROFESSORES
(
    MATRICULA_PROFESSOR INT PRIMARY KEY,
    NOME_PROFESSOR VARCHAR(100) NOT NULL,
    CODIGO_DISCIPLINA INT NOT NULL,
    CONSTRAINT FK_PROFESSORES_DISCIPLINAS
        FOREIGN KEY (CODIGO_DISCIPLINA) REFERENCES DISCIPLINAS(CODIGO_DISCIPLINA)
);

CREATE TABLE EMPRESTIMOS
(
    MATRICULA_ALUNO INT NOT NULL,
    ISBN INT NOT NULL,
    DATA_EMPRESTIMO DATE NOT NULL,
    PRIMARY KEY (MATRICULA_ALUNO, ISBN, DATA_EMPRESTIMO),
    CONSTRAINT FK_ALUNOS_EMPRESTIMOS
        FOREIGN KEY (MATRICULA_ALUNO) REFERENCES ALUNOS(MATRICULA_ALUNO),
    CONSTRAINT FK_ISBN_EMPRESTIMOS
        FOREIGN KEY (ISBN) REFERENCES LIVROS(ISBN)
);

CREATE TABLE ALUNOS_CURSOS
(
    MATRICULA_ALUNO INT NOT NULL,
    CODIGO_CURSO INT NOT NULL,
    PRIMARY KEY (MATRICULA_ALUNO, CODIGO_CURSO),
    CONSTRAINT FK_ALUNOS_CURSOS
        FOREIGN KEY (MATRICULA_ALUNO) REFERENCES ALUNOS(MATRICULA_ALUNO),
    CONSTRAINT FK_CURSOS_CURSOS
        FOREIGN KEY (CODIGO_CURSO) REFERENCES CURSOS(CODIGO_CURSO)
);

CREATE TABLE CURSOS_DISCIPLINAS
(
CODIGO_CURSO INT NOT NULL,
CODIGO_DISCIPLINA INT NOT NULL,
CONSTRAINT PK_CURSOS_DISCIPLINAS PRIMARY KEY (CODIGO_CURSO, CODIGO_DISCIPLINA),
CONSTRAINT FK_CC FOREIGN KEY (CODIGO_CURSO) REFERENCES CURSOS(CODIGO_CURSO),
CONSTRAINT FK_CD FOREIGN KEY (CODIGO_DISCIPLINA) REFERENCES DISCIPLINAS(CODIGO_DISCIPLINA)
);