CREATE  DATABASE BDPRODUTO 
USE BDPRODUTO 

CREATE TABLE VENDEDOR 
(CODV INT NOT NULL PRIMARY KEY, 
 NOME VARCHAR(30), 
 SALARIO MONEY) 

 CREATE TABLE FORNECEDOR 
( CODF INT NOT NULL PRIMARY KEY, 
  NOMEF VARCHAR(30)) 

  CREATE TABLE CLIENTE 
(CODCLI INT NOT NULL PRIMARY KEY, 
 NOMECLI VARCHAR(30)) 

 CREATE TABLE PRODUTO 
(CODP INT NOT NULL PRIMARY KEY, 
 NOMEP VARCHAR(30), 
 ESTOQUE INT, 
 CODF INT , 
 FOREIGN KEY (CODF) REFERENCES FORNECEDOR) 

 CREATE  TABLE VENDER 
(CODV INT NOT NULL,  
 CODP INT NOT NULL, 
  DATAVENDA SMALLDATETIME, 
 QTDEVENDA INT, 
 VALORVENDA MONEY, 
 COMISSAO INT, 
 PRIMARY KEY(CODV,CODP), 
 FOREIGN KEY (CODV) REFERENCES VENDEDOR, 
 FOREIGN KEY (CODP) REFERENCES PRODUTO) 

 CREATE TABLE COMPRAR  
(CODCLI INT NOT NULL,  
 CODP INT NOT NULL, 
 DATACOMPRA SMALLDATETIME, 
 FORMAPAGTO VARCHAR(20), 
 VALORCOMPRA MONEY, 
PRIMARY KEY(CODCLI,CODP), 
FOREIGN KEY (CODCLI) REFERENCES CLIENTE, 
FOREIGN KEY (CODP) REFERENCES PRODUTO) 